### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Jvr2022** [wojtas3422/dotfiles#1]
Hey do you know wer xanondev is I tried to contact him using discord but it looks like he is gone?

**Comment by wojtas3422** [comment]
Add me on discord: `wojtas3422`

**Comment by Jvr2022** [comment]
Ok

**Comment by Jvr2022** [comment]
You are not accepting friend requests

**Comment by Jvr2022** [comment]
Add me: `jvr2022_github`
